### ISSUE TITLE
As a back-end engineer, I want to study calendar library from react native to build the calendar page in react native.

### ISSUE THREAD

**Issue by rsori013** [CS180-spring/cs180-22-jymbois#15]
Priority : 10

Story Points: 5 hours

Test case:
Back-end engineer knows the knowledge of calendart library from react native.

This will be under 
As a user, I want to see a calendar, so that I can see the dates of the month.#4

**Comment by GodfreyL3** [comment]
Learning React-Native First. Then will research "calendart" library.
